components:
  schemas:
    Default:
      properties:
        code:
          format: int32
          type: integer
      type: object
info:
  contact:
    email: example@example.example
    name: ''
  description: OpenApiSample
  title: OpenApiSample
  version: 0.0.5
openapi: 3.1.0
paths:
  /foo:
    get:
      description: Documentation goes here.
      operationId: foo
      requestBody:
        content:
          application/json:
            schema:
              $ref:
                properties:
                  baz:
                    description: Bar the door.
                    introduced_at: 4
                    properties:
                      bar:
                        description: asdf
                        introduced_at: 5
                        type: string
                    type: object
                  foo:
                    description: This is a foo.
                    type: string
                required:
                - foo
                - baz
                type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref:
                  properties:
                    bar:
                      description: bar bar
                      introduced_at: 5
                      type: string
                    foo_result:
                      description: Result of a foo.
                      type: string
                  type: object
          description: OK
      tags:
      - none
servers:
- url: http://localhost
tags:
- name: none
