components:
  schemas:
    Default:
      properties:
        code:
          format: int32
          type: integer
      type: object
info:
  contact:
    email: example@example.example
    name: ''
  description: OpenApiSample
  title: OpenApiSample
  version: 0.0.5
openapi: 3.1.0
paths:
  /foo:
    get:
      description: Documentation goes here.
      operationId: foo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Default'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Default'
          description: OK
      tags:
      - none
servers:
- url: http://localhost
tags:
- name: none
